- name: Start postgres and enable ssh-login
  hosts: all
  user: root

  vars_files:
    - "../../config.yml" # the user-generated config
    - config.yml

  tasks:
    - name: start postgresql
      service: name=postgresql state=started

    - name: enable ssh login for postgres user
      authorized_key: user=postgres  key="{{ ssh_keys }}"
