- name: Setup dbs
  hosts: all
  user: postgres

  vars_files:
    - "../../config.yml"
    - config.yml

  tasks:
    - name: create database users
      postgresql_user: name=$app_user password=$pgpass

    - name: create databases 
      postgresql_db: name=$app_user owner=$app_user state=present
